version: '3'

services:
  mongodb:
    image: mongodb/mongodb-community-server
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  website:
    build: 
      context: .
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: sh -c "cargo watch -x run"